symbol/symbol-docs

- source/guides/transaction/atomic-cross-chain-swap-between-NEM-public-and-private-chain.rst
Changed "public" to "private" in Alice's first Tx/announcement.
> Update of text regarding private blockchain

- source/conf.py
fix for the issue => [Fix WARNING: logo file 'logo\-nem\.svg' does not exist](https://github.com/nemtech/nem2-docs/issues/24)
> Fix Warning "logo file 'logo-nem.svg' does not exist"

- source/concepts/account.rst
- source/concepts/aggregate-transaction.rst
- source/concepts/block.rst
- source/concepts/cross-chain-swaps.rst
- source/concepts/mosaic.rst
- source/concepts/multisig-account.rst
- source/concepts/namespace.rst
- source/concepts/node.rst
- source/concepts/transaction.rst
- source/concepts/transfer-transaction.rst
Added schemas to the "built-in feature / protocol"
refs: #47
> Add schemas

- source/concepts/aggregate-transaction.rst
Example states that Alice is purchasing tickets using Euros
> Fix currency to follow currency.euro

- source/concepts/mosaic.rst
- source/guides/account/getting-account-information.rst
- source/guides/mosaic/creating-a-mosaic.rst
- source/guides/mosaic/getting-mosaic-information.rst
- source/guides/namespace/getting-namespace-information.rst
- source/guides/transaction/sending-a-transfer-transaction.rst
- source/resources/examples/cli/mosaic/GettingMosaicInformation.sh
- source/resources/examples/cli/namespace/GettingNamespaceInformation.sh
- source/resources/examples/javascript/mosaic/GettingMosaicInformation.js
- source/resources/examples/javascript/namespace/GettingNamespaceInformation.js
- source/resources/examples/javascript/transaction/SendingATransferTransactionWithMultipleMosaics.js
- source/resources/examples/typescript/mosaic/GettingMosaicInformation.ts
- source/resources/examples/typescript/namespace/GettingNamespaceInformation.ts
- source/resources/examples/typescript/transaction/SendingATransferTransactionWithMultipleMosaics.ts
> How to create a non expirable mosaic

- source/api.rst
- source/concepts/block.rst
- source/concepts/cross-chain-swaps.rst
- source/concepts/cryptography.rst
- source/concepts/mosaic.rst
- source/concepts/multisig-account.rst
- source/concepts/namespace.rst
- source/concepts/node.rst
- source/resources/collections/swagger.yaml
> 119 responses description

- source/_templates/index.html
- source/cli.rst
> 126 cli reference

- .tx/config
- source/concepts/account-filter.rst
- source/guides/account/preventing-spam-attacks-with-account-filters.rst
- source/resources/examples/typescript/account/FilteringByAddressAllowList.ts
- source/resources/examples/typescript/account/FilteringByAddressRemoveFilter.ts
- source/resources/examples/typescript/account/FilteringByMosaicBlockList.ts
> Added account filters guide

- source/concepts/mosaic.rst
> Fixed mosaic supply range

- source/resources/collections/openapi3.yaml
- source/resources/collections/swagger2.yaml
Issue #192 
Fixed `MerkleProofInfoDTO` in swagger files
> Merkle Proof Info DTO Fixes

- source/resources/collections/openapi3.yaml
- source/resources/collections/swagger2.yaml
> Renamed account properties to account restrictions (REST)

- source/api.rst
- source/resources/collections/openapi3.yaml
- source/resources/collections/swagger2.yaml
> catapult-rest 0.7.17 docs

- source/concepts/account-restriction.rst
- source/concepts/aggregate-transaction.rst
- source/concepts/block.rst
- source/concepts/cross-chain-swaps.rst
- source/concepts/harvesting.rst
- source/concepts/metadata.rst
- source/concepts/mosaic-restriction.rst
- source/concepts/mosaic.rst
- source/concepts/multisig-account.rst
- source/concepts/namespace.rst
- source/concepts/receipt.rst
- source/concepts/transfer-transaction.rst
> Elephant 3 catbuffer protocol changes

- source/api.rst
Added elephant 3 status errors and catapult-rest installation instructions
> Elephant 3 status errors

- source/concepts/consensus-algorithm.rst
- source/concepts/mosaic.rst
- source/concepts/namespace.rst
- source/concepts/transaction.rst
- source/conf.py
> Added dynamic rental fees

- source/_static/css/custom.css
- source/_static/js/custom.js
- source/_templates/include/navbar-right.html
- source/_templates/include/searchbox.html
- source/_templates/navbar.html
- source/concepts/mosaic.rst
- source/concepts/namespace.rst
> Added mobile search

- source/concepts/mosaic.rst
- source/concepts/namespace.rst
- source/getting-started/setup-workstation.rst
> Update rental fees docs

- source/cli.rst
- source/getting-started/setup-workstation.rst
- source/resources/examples/bash/multisig/ModifyingAMultisigAccount.sh
- source/resources/examples/bash/restriction/AnnouncingAccountAddressRestrictionTransaction.sh
- source/resources/examples/bash/restriction/AnnouncingAccountMosaicRestrictionTransaction.sh
- source/resources/examples/bash/restriction/AnnouncingAccountOperationRestrictionTransaction.sh
- source/resources/examples/bash/secretlock/AnnouncingASecretLockTransaction.sh
- source/resources/examples/bash/secretlock/AnnouncingASecretProofTransaction.sh
- source/resources/examples/typescript/secretlock/CrossChainSwap.ts
> Added CLI 0.13.4 reference

- source/concepts/transaction.rst
fix typo in MultisigAccountModificationTransaction
> fix typo in MultisigAccountModificationTransaction

- source/_templates/endpoints.html
- source/api.rst
- source/cli.rst
- source/guidelines/sdk-development.rst
- source/guidelines/sdk-documentation.rst
- source/guides/blockchain/listening-new-blocks.rst
- source/guides/monitor/monitoring-a-transaction-status.rst
> Complete WebSockets docs

- source/resources/examples/typescript/metadata/GettingMetadataEntriesAccount.ts
- source/resources/examples/typescript/metadata/GettingMetadataEntriesAccountByKey.ts
- source/resources/examples/typescript/metadata/GettingMetadataEntriesAccountByKeyAndSender.ts
- source/resources/examples/typescript/metadata/GettingMetadataEntriesMosaic.ts
- source/resources/examples/typescript/metadata/GettingMetadataEntriesMosaicByKey.ts
- source/resources/examples/typescript/metadata/GettingMetadataEntriesMosaicByKeyAndSender.ts
- source/resources/examples/typescript/metadata/GettingMetadataEntriesNamespace.ts
- source/resources/examples/typescript/metadata/GettingMetadataEntriesNamespaceByKey.ts
- source/resources/examples/typescript/metadata/GettingMetadataEntriesNamespaceByKeyAndSender.ts
- fix metadata example code typo
> metadata typo

- README.md
- source/index.rst
> Updated copy landing

- source/concepts/cryptography.rst
> Added signature

- source/guidelines/sdk-development.rst
- source/guidelines/sdk-documentation.rst
> Updated sdk development guide

- source/_static/js/custom.js
- source/guidelines/translating-the-documentation.rst
Replaced Transifiex project name.
> replace nem2docs -> symboldocs

- source/cli.rst
- source/concepts/data-validation.rst
- source/resources/examples/bash/monitor/GettingServerInfo.sh
- source/resources/examples/bash/monitor/GettingServerStorage.sh
- source/resources/examples/bash/node/GettingHealth.sh
- source/resources/examples/bash/node/GettingInfo.sh
- source/resources/examples/bash/node/GettingServerInfo.sh
- source/resources/examples/bash/node/GettingStorageInfo.sh
> Added cli 0.18.1 docs

- source/guides/mosaic/creating-a-mosaic.rst
- source/guides/mosaic/modifying-mosaic-supply.rst
- source/resources/examples/java/src/test/java/symbol/guides/examples/mosaic/CreatingAMosaic.java
- source/resources/examples/java/src/test/java/symbol/guides/examples/mosaic/ModifyingMosaicSupply.java
- source/resources/examples/typescript/account/GettingTheAmountOfAssetsSentToAnAccount.js
- source/resources/examples/typescript/aggregate/CosigningAggregateBondedTransactions.js
- source/resources/examples/typescript/aggregate/CosigningAggregateBondedTransactionsAutomaticallyWithConstraints.js
- source/resources/examples/typescript/blockchain/CalculatingMerkleRootFromBlockTransactions.js
- source/resources/examples/typescript/blockchain/GettingTheMosaicIdentifierBehindANamespaceWithReceipts.js
- source/resources/examples/typescript/blockchain/ValidatingTransactionWithinBlock.js
- source/resources/examples/typescript/metadata/UpdatingMetadataEntriesRetrievePreviousValue.js
- source/resources/examples/typescript/metadata/UpdatingMetadataEntriesService.js
- source/resources/examples/typescript/monitor/TurningTheAsynchronousTransactionAnnouncementIntoSynchronous.js
- source/resources/examples/typescript/mosaic/CreatingAMosaic.js
- source/resources/examples/typescript/mosaic/CreatingAMosaic.ts
- source/resources/examples/typescript/mosaic/ModifyingMosaicSupply.js
- source/resources/examples/typescript/mosaic/ModifyingMosaicSupply.ts
- source/resources/examples/typescript/transfer/DecodingAnEncryptedMessage.js
- Implemented mosaic creation snippets for Java.
- Enhanced mosaic creation guides.
- Compiled some missing ts examples.
> Added mosaic snippets (java)

- source/cli.rst
- source/resources/examples/bash/accountlink/ActivatingDelegatedHarvestingAccountLink.sh
- source/resources/examples/bash/mosaic/ModifyingMosaicSupply.sh
- source/resources/examples/bash/multisig/ModifyingAMultisigAccount.sh
- source/resources/examples/bash/namespace/LinkNamespaceAddress.sh
- source/resources/examples/bash/namespace/LinkNamespaceMosaic.sh
- source/resources/examples/bash/restriction/AnnouncingAccountAddressRestrictionTransaction.sh
- source/resources/examples/bash/restriction/AnnouncingAccountMosaicRestrictionTransaction.sh
- source/resources/examples/bash/restriction/AnnouncingAccountOperationRestrictionTransaction.sh
Docs updated for CLI next version
> Updated CLI docs 0.18.2

- source/getting-started/setup-workstation.rst
- source/guides/network/running-a-test-net-node.rst
Updated the wallet link and added info on how to check if a peer node is running.
> Updated wallet link

- source/resources/examples/typescript/metadata/UpdatingMetadataEntriesService.js
- source/resources/examples/typescript/metadata/UpdatingMetadataEntriesService.ts
> Fix createbonded

- source/guides/network/configuring-node-properties.rst
- source/guides/network/creating-a-private-test-net.rst
- source/guides/network/running-a-test-net-node.rst
> Updated network guide

- source/concepts/block.rst
- source/concepts/transaction.rst
Reorganized rollbacks concept under blocks to prepare for finalization changes.
> Improved block.rst

- source/guides/metadata/assigning-metadata-entries-to-a-mosaic.rst
- source/guides/namespace/extending-a-namespace-registration-period.rst
- source/guides/namespace/registering-a-namespace.rst
- source/resources/examples/bash/namespace/RegisteringANamespace.sh
- source/resources/examples/typescript/namespace/RegisteringANamespace.ts
> Fix namespace duration

- source/concepts/harvesting.rst
- source/guides/network/configuring-network-properties.rst
- source/guides/network/configuring-node-properties.rst
> Updated 0.9.6 config

- source/concepts/block.rst
- source/guides/network/configuring-network-properties.rst
- source/serialization/account_link.rst
- source/serialization/coresystem.rst
- source/serialization/lock_secret.rst
> Update txs schemas 0.9.6.2

- source/getting-started/setup-workstation.rst
This is the Faucet address as shown in http://faucet-96x-01.symboldev.network/
Does this address change with every testnet iteration?
> Update Faucet address in setup-workstation.rst

- source/resources/examples/typescript/metadata/GettingMetadataEntriesAccount.js
- source/resources/examples/typescript/metadata/GettingMetadataEntriesAccount.ts
- source/resources/examples/typescript/metadata/GettingMetadataEntriesMosaic.js
- source/resources/examples/typescript/metadata/GettingMetadataEntriesMosaic.ts
- source/resources/examples/typescript/metadata/GettingMetadataEntriesNamespace.js
- source/resources/examples/typescript/metadata/GettingMetadataEntriesNamespace.ts
- source/resources/examples/typescript/metadata/UpdatingMetadataEntriesRetrievePreviousValue.js
- source/resources/examples/typescript/metadata/UpdatingMetadataEntriesRetrievePreviousValue.ts
- source/resources/examples/typescript/metadata/UpdatingMetadataEntriesService.js
- source/resources/examples/typescript/metadata/UpdatingMetadataEntriesService.ts
- source/resources/examples/typescript/package-lock.json
- source/resources/examples/typescript/package.json
> 0.9.6 code examples update

- .travis.yml
- source/guides/account/getting-the-amount-of-assets-sent-to-an-account.rst
- source/guides/account/reading-transactions-from-an-account.rst
- source/guides/aggregate/adding-cosginatures-aggregate-complete.rst
- source/guides/aggregate/creating-an-escrow-contract-with-aggregate-bonded-transaction.rst
- source/guides/aggregate/sending-a-multisig-transaction.rst
- source/guides/aggregate/sending-multiple-transactions-together-with-aggregate-complete-transaction.rst
- source/guides/aggregate/signing-announced-aggregate-bonded-transactions-automatically.rst
- source/guides/aggregate/signing-announced-aggregate-bonded-transactions.rst
- source/resources/examples/java/build.gradle
- source/resources/examples/java/src/test/java/symbol/guides/examples/account/GettingConfirmedTransactions.java
- source/resources/examples/java/src/test/java/symbol/guides/examples/account/GettingTheAmountOfAssetsSentToAnAccount.java
- source/resources/examples/java/src/test/java/symbol/guides/examples/aggregate/AddingCosignaturesAggregateComplete.java
- source/resources/examples/java/src/test/java/symbol/guides/examples/aggregate/CosigningAggregateBondedTransactions.java
- source/resources/examples/java/src/test/java/symbol/guides/examples/aggregate/CosigningAggregateBondedTransactionsAutomatically.java
- source/resources/examples/java/src/test/java/symbol/guides/examples/aggregate/CosigningAggregateBondedTransactionsAutomaticallyWithConstraints.java
- source/resources/examples/java/src/test/java/symbol/guides/examples/aggregate/CreatingAnEscrowContractWithAggregateBondedTransaction.java
- source/resources/examples/java/src/test/java/symbol/guides/examples/aggregate/GettingPartialTransactions.java
- source/resources/examples/java/src/test/java/symbol/guides/examples/aggregate/SendingAMultisigTransactionAggregateBonded.java
- source/resources/examples/java/src/test/java/symbol/guides/examples/aggregate/SendingAMultisigTransactionAggregateComplete.java
- source/resources/examples/java/src/test/java/symbol/guides/examples/aggregate/SendingMultipleTransactionsTogetherWithAggregateCompleteTransaction.java
- source/resources/examples/java/src/test/java/symbol/guides/examples/metadata/GettingMetadataEntriesAccount.java
- source/resources/examples/java/src/test/java/symbol/guides/examples/metadata/GettingMetadataEntriesMosaic.java
- source/resources/examples/java/src/test/java/symbol/guides/examples/metadata/GettingMetadataEntriesNamespace.java
- source/resources/examples/java/src/test/java/symbol/guides/examples/restriction/GettingMosaicAddressRestrictions.java
- source/resources/examples/java/src/test/java/symbol/guides/examples/restriction/GettingMosaicGlobalRestrictions.java
Aggregate java examples. Part of the https://github.com/nemtech/symbol-docs/issues/101 task.
> Added aggregate java examples

- source/api.rst
- source/guides/migration/migrating-from-nem-to-symbol.rst
- source/guides/monitor/turning-the-asynchronous-transaction-announcement-into-synchronous.rst
- source/guides/network/configuring-node-properties.rst
- source/guides/network/creating-a-private-test-net.rst
- source/guides/network/using-symbol-bootstrap.rst
- source/references/overview.rst
- source/server.rst
> Update docs to use symbol-bootstrap instead of catapult-service-bootstrap

- source/guides/network/creating-a-private-test-net.rst
- source/guides/network/using-symbol-bootstrap.rst
> Update symbol-bootstrap docs to v0.2.0

- .travis.yml
- source/resources/examples/typescript/package-lock.json
- source/resources/examples/typescript/package.json
Updated sdk version to release 0.22.0
> Installing node 12

- source/guides/network/using-symbol-bootstrap.rst
Added known problem and workaround (user's permissions for docker daemon).
> Added troubleshooting section.

- source/concepts/harvesting.rst
Local, Remote and Delegated. Links to setup
guides will be added once they are available.
> Clarify all 3 kinds of harvesting

- source/guides/network/running-a-test-net-node.rst
> Provide hardware requirements to run nodes

- source/concepts/cryptography.rst
> Revamp crypto concept

- source/_static/config-harvesting.properties.html
- source/_static/config-inflation.properties.html
- source/_static/config-network.properties.html
- source/_static/config-node.properties.html
- source/_static/config-user.properties.html
> Update static property tables

- source/_static/config-harvesting.properties.html
- source/_static/config-inflation.properties.html
- source/_static/config-network.properties.html
- source/_static/config-node.properties.html
- source/_static/config-user.properties.html
- source/getting-started/setup-workstation.rst
- source/guides/migration/migrating-from-nem-to-symbol.rst
- source/guides/network/supernode-enrollment.rst
- source/guides/network/using-symbol-bootstrap.rst
- source/index.rst
- source/references/overview.rst
Remove banners saying that mainnet is not ready yet.
Remove talk of "future" mainnet.
Use links to mainnet resources instead of testnet.
Add mainnet bootstrap presets.
> Mainnet launch

- source/guides/network/supernode-enrollment.rst
The enrollment procedure has been changed so the guide needed updating. 
Fixes #642
> Update Supernode enrollment guide

- source/locale/ja/LC_MESSAGES/getting-started/first-application.po
> small fix locale/ja in first-application.po

- source/guides/network/running-a-symbol-node-manually.rst
- source/guides/network/running-a-symbol-node.rst
- source/serialization/coresystem.rst
Both Manual and using Bootstrap.
Fixes #608
> feat: Add voting key renewal instructions

- source/conf.py
- source/guides/network/index.rst
- source/guides/network/maintaining-a-symbol-node.rst
- source/guides/network/running-a-symbol-node-manually.rst
- source/guides/network/running-a-symbol-node.rst
- source/server.rst
- How to upgrade your node
- How to renew your node's voting keys
> Node maintenance guide

- source/concepts/block.rst
- source/concepts/fees.rst
- source/concepts/receipt.rst
- source/guides/exchanges/exchange-REST-troubleshooting.rst
- source/guides/exchanges/exchange-integration.rst
- source/guides/exchanges/index.rst
> REST troubleshooting guide for Exchanges

- source/contribute/directory.md
First push from HackMD to GitHub docs repo.
> Initial import

- source/handbook/all-coding-guidelines.rst
- source/handbook/contribution-guidelines.rst
- source/handbook/cpp-coding-guidelines.rst
- source/handbook/index.rst
- source/handbook/javascript-coding-guidelines.rst
- source/handbook/python-coding-guidelines.rst
need to improve (add?) navigation, but content should be mostly done. 
so made review!
> coding guidelines v2

- docs/CNAME
Update the cname from ``docs.symbolplatform.com`` to ``docs.symbol.dev``
> fix: update cname

- .tx/config
- source/locale/ja/LC_MESSAGES/contribute/contributing-docs.po
- source/locale/ja/LC_MESSAGES/guides/blockchain/global-mosaic-supply.po
- source/locale/ja/LC_MESSAGES/guides/migration/post-launch-optin-xym-retrieval.po
Config file was referencing serialization files which have been deleted long ago
(When serialization docs were automated).
Also, added some missing .po files.
These problems were ignored by Travis but not by Jenkins, which was failing builds.
> Update Transifex files

- source/guides/exchanges/exchange-REST-troubleshooting.rst
> fix: typo in exchange-REST-troubleshooting.rst

- source/concepts/overview.rst
In relation to #838 -- propose linking to the Technical Reference document at the bottom of the Technology page.
> Add link to the Technical Reference Document

- source/conf.py
- source/guides/migration/post-launch-optin-xym-retrieval.rst
problem: build is failing due to broken links
solution: fix broken links
> [docs] fix: broken links

- .tx/config
- scripts/ci/deploy.sh
- scripts/ci/transifex.sh
problem: pip Transifex client is outdated and cannot upload the source
solution: update to the latest Transifex cli
> [docs] fix: update Transifex to use the latest cli
